@framework@if (mode === 'dev') {
  <!-- Attention! -->
  <!-- This file is auto-generated by the build process. -->
  <!-- Any changes directly to this file will be overrided! -->
  @framework@include('styles-dev.res')
}
@framework@if (mode !== 'dev') {
  <!-- TODO: adding  production styles:  minified and gZipped-->
  <link href="/vendor/angular-ui-bootstrap/ui-bootstrap-csp.css" rel="stylesheet">
  <link href="/vendor/bootstrap/bootstrap.min.css" rel="stylesheet">
  <link href="/common/css/app.css" rel="stylesheet">
}

<style type="text/css">
[ng\:cloak], [ng-cloak], .ng-cloak {
	display: none !important;
}
</style>
